# Generated by Django 5.1.3 on 2024-11-27 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('shortDescription', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('imgSrc', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='draft')),
                ('dateModerated', models.DateField(null=True)),
                ('dateSaved', models.DateField(null=True)),
                ('satelliteName', models.CharField(max_length=150, null=True)),
                ('flyDate', models.DateField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userAccess', to=settings.AUTH_USER_MODEL)),
                ('moder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderAccess', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(null=True)),
                ('idAssembly', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab1_app.assembly')),
                ('idComp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab1_app.component')),
            ],
            options={
                'unique_together': {('idComp', 'idAssembly')},
            },
        ),
    ]
