# Generated by Django 5.1.3 on 2025-02-25 20:38

import django.db.models.deletion
import lab1_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shortDescription', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('imgSrc', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(unique=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Модератор')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Админ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', lab1_app.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='draft')),
                ('dateModerated', models.DateField(null=True)),
                ('dateSaved', models.DateField(null=True)),
                ('satelliteName', models.CharField(max_length=150, null=True)),
                ('flyDate', models.DateField(null=True)),
                ('orbit', models.IntegerField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userAccess', to=settings.AUTH_USER_MODEL)),
                ('moder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderAccess', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('idAssembly', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab1_app.assembly')),
                ('idComp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab1_app.component')),
            ],
            options={
                'unique_together': {('idComp', 'idAssembly')},
            },
        ),
    ]
