# Generated by Django 5.1.3 on 2024-12-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='orbit',
            field=models.IntegerField(null=True),
        ),
    ]
