# Generated by Django 5.1.3 on 2025-02-26 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='dateModerated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='dateSaved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='flyDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='moder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='orbit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='satelliteName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='imgSrc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
