# Generated by Django 5.1.3 on 2025-02-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_app', '0002_alter_assembly_datemoderated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mm',
            old_name='idComp',
            new_name='component',
        ),
        migrations.AlterUniqueTogether(
            name='mm',
            unique_together={('component', 'idAssembly')},
        ),
    ]
