# Generated by Django 5.1.3 on 2025-02-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_app', '0003_rename_idcomp_mm_component_alter_mm_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
