# Generated by Django 5.1.3 on 2025-02-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_app', '0004_assembly_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='orbit',
        ),
    ]
